-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON



CREATE TABLE employees (
	id bigint NOT NULL,
	name varchar(50),
	hire_date timestamp(0)
) ;
ALTER TABLE employees ADD PRIMARY KEY (id);
