-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA IF NOT EXISTS lolu;
ALTER SCHEMA lolu OWNER TO lolu;

SET search_path = lolu,public;


CREATE TABLE test_varray (
	id bigint NOT NULL,
	name varchar(50),
	numbers NUMBER_ARRAY,
	created_date timestamp(0)
) ;
ALTER TABLE test_varray ADD PRIMARY KEY (id);


CREATE TABLE test_object (
	id bigint NOT NULL,
	customer_name varchar(100),
	address ADDRESS_TYPE,
	created_date timestamp(0)
) ;
ALTER TABLE test_object ADD PRIMARY KEY (id);


CREATE TABLE test_nested (
	id bigint NOT NULL,
	title varchar(100),
	tags STRING_LIST,
	created_date timestamp(0)
) ;
CREATE UNIQUE INDEX sys_c008226 ON test_nested (tags);
ALTER TABLE test_nested ADD PRIMARY KEY (id);
