-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;service_name=XEPDB1;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA IF NOT EXISTS lolu;
ALTER SCHEMA lolu OWNER TO lolu;

SET search_path = lolu,public;


CREATE TABLE test_varray_full (
	id bigint NOT NULL,
	name varchar(100),
	numbers decimal(10,2)[],
	created_date TIMESTAMP(6)
) ;
ALTER TABLE test_varray_full ADD PRIMARY KEY (id);


CREATE TABLE test_object_full (
	id bigint NOT NULL,
	customer_name varchar(100),
	address jsonb,
	created_date TIMESTAMP(6)
) ;
ALTER TABLE test_object_full ADD PRIMARY KEY (id);


CREATE TABLE test_nested_full (
	id bigint NOT NULL,
	post_title varchar(100),
	tags varchar(500)[],
	created_date TIMESTAMP(6)
) ;
CREATE UNIQUE INDEX sys_c008234 ON test_nested_full (tags);
ALTER TABLE test_nested_full ADD PRIMARY KEY (id);
